name = "IterativeLearningControl"
uuid = "528a9aa3-4044-4660-82a5-c2ef7f1e15dc"
authors = ["Fredrik Bagge Carlson"]
version = "1.0.0-DEV"

[deps]
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
